---
services:
  mysql:
    ports:
      - 3306:3306
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: sysadmin  # change!
      MYSQL_PASSWORD: Changeme  # change!
  semaphore:
    container_name: ansiblesemaphore
    
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: sysadmin  # change!
      SEMAPHORE_DB_PASS: Changeme   # change!
      SEMAPHORE_DB_HOST: mysql 
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: Change_me  # change!
      SEMAPHORE_ADMIN_NAME: sysadmin  # change !
      SEMAPHORE_ADMIN_EMAIL: sysadmin@localhost  # change!
      SEMAPHORE_ADMIN: sysadmin  # change!
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: aGfcDr4CRTrgjgiugiugiuikughihgig4QTe8alAv8=  # change!
      ANSIBLE_HOST_KEY_CHECKING: false  # (optional) change to true if you want to enable host key checking
    volumes:
      - ./inventory/:/inventory:ro
      - ./authorized-keys/:/authorized-keys:ro
      - ./config/:/etc/semaphore:rw
    restart: unless-stopped
    depends_on:
      - mysql
volumes:
  semaphore-mysql: